### ISSUE TITLE
DatabaseConfig not working without @Bean annotation

### ISSUE THREAD

**Issue by jerryOkafor** [hantsy/spring-kotlin-coroutines-sample#1]
after hrs of troubleshooting, I figure out that without @Bean annotation, spring is not able to pick the Config. Also refer to the example in this link.
https://www.baeldung.com/spring-data-r2dbc

```
@Bean
override fun connectionFactory(): ConnectionFactory {
        return PostgresqlConnectionFactory(
                PostgresqlConnectionConfiguration.builder()
                        .host("localhost")
                        .database("test")
                        .username("user")
                        .password("password")
                        .build()
        )
    }
```

**Comment by hantsy** [comment]
This repository is to experience the Kotlin Coroutine features.

The Spring Data R2dbc in this project is based on an older version. **Spring Data R2dbc 1.2 introduced plenty of breaking changes**. If you like to explore the newest Spring Data R2dbc features since 1.2(included in Spring Boot 2.4), please go to https://github.com/hantsy/spring-r2dbc-sample.
